// DealHunter AI V1.12 — universal product search + lowest verified web prices
// Secrets required: BRAVE_API_KEY, SCANNER_KEY
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,x-dealhunter-key','Access-Control-Allow-Methods':'GET,POST,OPTIONS'};
const json=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...CORS,'content-type':'application/json;charset=utf-8'}});
const money=x=>{if(x==null||x==='')return null;let z=String(x).trim().replace(/\s/g,'').replace(/[^0-9.,-]/g,'');if(!z)return null;if(z.includes(',')&&z.includes('.')){if(z.lastIndexOf(',')>z.lastIndexOf('.'))z=z.replace(/\./g,'').replace(',','.');else z=z.replace(/,/g,'')}else if(z.includes(','))z=z.replace(',','.');let n=Number(z);return Number.isFinite(n)?n:null};
const med=a=>{a=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return null;let m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
const norm=s=>(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
const host=u=>{try{return new URL(u).hostname.replace(/^www\./,'')}catch{return''}};
const resolve=(base,u)=>{try{return new URL(u,base).toString()}catch{return base}};
const ACCESSORY=['cover','custodia','supporto','stand','base','ricambio','pellicola','cavo','adattatore','case','vetro temperato','caricatore','borsa','tracolla','corde'];
const GENERIC=['prezzo','prezzi','offerte','offerta','catalogo','categoria','categorie','ricerca','risultati','annunci','prodotti','shopping','confronta','migliori','shop'];
function skipHost(h){return /(^|\.)google\./i.test(h)||/youtube\./i.test(h)||/facebook\./i.test(h)||/instagram\./i.test(h)||/tiktok\./i.test(h)||/pinterest\./i.test(h)}
function urlGeneric(u){try{let x=new URL(u),p=(x.pathname+' '+x.search).toLowerCase();return /\/(search|ricerca|catalog|catalogo|category|categoria|listing|risultati)(\/|\?|$)/.test(p)||/[?&](q|query|search|keyword)=/.test(p)}catch{return true}}
function cleanTitle(s){return String(s||'').replace(/\s+/g,' ').split(/\s+[|–—]\s+/)[0].split(/\s+-\s+(?:Amazon|eBay|MediaWorld|Unieuro|Euronics|Trony|Idealo|Trovaprezzi)\b/i)[0].trim().slice(0,190)}
function toks(s){return norm(s).split(' ').filter(x=>x.length>1&&!GENERIC.includes(x))}
function modelToks(s){return toks(s).filter(x=>/\d/.test(x)&&x.length>=2)}
function relevant(term,title){let a=toks(term),b=toks(title);if(!a.length||!b.length)return false;let hit=a.filter(x=>b.includes(x)).length;return hit>=Math.max(1,Math.ceil(a.length*.5))}
function similarity(a,b){let x=toks(a),y=toks(b);if(!x.length||!y.length)return 0;let hit=x.filter(t=>y.includes(t)).length,score=hit/Math.max(2,Math.min(x.length,8));let xm=modelToks(a),ym=modelToks(b);if(xm.length&&ym.length&&!xm.some(t=>ym.includes(t)))score*=.15;return score}
function accessoryMismatch(term,title){let q=norm(term),t=norm(title);return ACCESSORY.some(w=>t.includes(w))&&!ACCESSORY.some(w=>q.includes(w))}
function genericTitle(title,term=''){let t=norm(title),q=norm(term);if(!t)return true;if(q&&(t===q||t.startsWith(q+' prezzo')||t.startsWith(q+' offerte')))return true;let h=GENERIC.filter(w=>t.includes(w)).length;return h>=2&&toks(t).length<8}
function walk(v,out=[]){if(!v)return out;if(Array.isArray(v)){for(const x of v)walk(x,out);return out}if(typeof v!=='object')return out;out.push(v);for(const x of Object.values(v))if(x&&typeof x==='object')walk(x,out);return out}
function typeProduct(v){let t=v?.['@type']??v?.type;return Array.isArray(t)?t.some(x=>String(x).toLowerCase()==='product'):String(t||'').toLowerCase()==='product'}
function productObjects(v){return walk(v,[]).filter(typeProduct)}
function firstImage(p){let i=p?.image??p?.thumbnail??p?.thumbnailUrl;if(Array.isArray(i))i=i[0];if(i&&typeof i==='object')i=i.url||i.contentUrl||i.imageUrl;return typeof i==='string'?i:''}
function availabilityBad(v){let a=String(v||'').toLowerCase();return /outofstock|soldout|discontinued|preorderclosed|non.?disponibile|esaurito|terminato/.test(a)}
function parseOffer(o){if(Array.isArray(o))o=o.find(x=>x&&typeof x==='object');if(!o||typeof o!=='object')return null;let price=money(o.price??o.lowPrice??o.sale_price??o.currentPrice??o.priceSpecification?.price),currency=o.priceCurrency||o.priceSpecification?.priceCurrency||o.currency||'EUR';if(!price||price<2||price>50000||String(currency).toUpperCase()!=='EUR')return null;let ship=null,sd=o.shippingDetails;if(Array.isArray(sd))sd=sd[0];if(sd){let sr=sd.shippingRate;if(Array.isArray(sr))sr=sr[0];ship=money(sr?.value??sr?.price)}return{price,ship,url:o.url||o.offerUrl||'',availability:String(o.availability||'')}}
function specific(title,url,term=''){if(!title||!url||urlGeneric(url)||genericTitle(title,term))return false;if(term&&(!relevant(term,title)||accessoryMismatch(term,title)))return false;return true}
function plainText(html){return String(html||'').replace(/<sup[^>]*>\s*([0-9]{2})\s*<\/sup>/gi,',$1').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<!--([\s\S]*?)-->/g,' ').replace(/&euro;|&#8364;/gi,'€').replace(/&nbsp;|&#160;/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
function pageUnavailable(html){let t=plainText(html).toLowerCase();return /prodotto\s+non\s+disponibile|articolo\s+non\s+disponibile|momentaneamente\s+non\s+disponibile|esaurito|sold\s*out|out\s*of\s*stock/.test(t)}
function visibleMainPrice(html){let t=plainText(html),re=/\b(prezzo|price)\b/gi,m,ban=/listino|rata|rate|mese|cashback|bonifico|finanziament|klarna|paypal|scalapay|a\s+partire|risparmi/i;while((m=re.exec(t))){let seg=t.slice(m.index,m.index+140),x=seg.match(/€\s*([0-9][0-9.]*?(?:,[0-9]{2})?)(?=\s|$)/i)||seg.match(/([0-9][0-9.]*?(?:,[0-9]{2})?)\s*€/i);if(x&&!ban.test(seg.slice(0,x.index))){let n=money(x[1]);if(n>=2&&n<=50000)return n}}return null}
function metaMainPrice(html){for(const re of [/property=[\"']product:price:amount[\"'][^>]*content=[\"']([0-9.,]+)[\"']/i,/itemprop=[\"']price[\"'][^>]*(?:content|value)=[\"']([0-9.,]+)[\"']/i,/name=[\"']twitter:data1[\"'][^>]*content=[\"'](?:€\s*)?([0-9.,]+)/i]){let m=html.match(re),n=m?money(m[1]):null;if(n>=2&&n<=50000)return n}return null}
function ogImage(html){let m=html.match(/property=[\"']og:image[\"'][^>]*content=[\"']([^\"']+)/i);return m?m[1]:''}
async function brave(q,env,count=10){let u='https://api.search.brave.com/res/v1/web/search?country=IT&search_lang=it&ui_lang=it-IT&count='+Math.min(10,count)+'&extra_snippets=true&text_decorations=false&q='+encodeURIComponent(q);let r=await fetch(u,{headers:{'X-Subscription-Token':env.BRAVE_API_KEY,'Accept':'application/json'}});if(!r.ok)throw new Error('Brave '+r.status);let j=await r.json();return (j.web?.results||[]).map(x=>({title:x.title||'',url:x.url||'',description:x.description||'',thumbnail:x.thumbnail||null,schemas:x.schemas||null,product:x.product||null,product_cluster:x.product_cluster||null,deep_results:x.deep_results||null}))}
function indexedProduct(x,term=''){if(!x?.url||skipHost(host(x.url))||urlGeneric(x.url))return null;for(const pool of [x.product,x.product_cluster,x.schemas,x.deep_results]){if(!pool)continue;for(const p of productObjects(pool)){let title=cleanTitle(p.name||p.title||x.title);if(!specific(title,p.url||x.url,term))continue;let of=parseOffer(p.offers||p.offer||p.priceSpecification);if(!of||availabilityBad(of.availability))continue;let u=resolve(x.url,p.url||of.url||x.url);if(urlGeneric(u))continue;return{title,url:u,domain:host(u),ask:of.price,ship:of.ship,image:firstImage(p)||x.thumbnail?.src||x.thumbnail?.original||'',availability:of.availability,priceSource:'BRAVE_PRODUCT_SCHEMA',priceVerified:false,shippingVerified:of.ship!==null,source:host(u),confidence:'medium'}}}return null}
async function pageProduct(x,term=''){let start=x.url;if(!specific(x.title,start,term)||skipHost(host(start)))return{item:null,hardReject:false};let r;try{r=await fetch(start,{redirect:'follow',headers:{'user-agent':'Mozilla/5.0 (compatible; DealHunterAI/1.12)','accept':'text/html,application/xhtml+xml'}})}catch{return{item:null,hardReject:false}}if(!r.ok)return{item:null,hardReject:false};let ct=r.headers.get('content-type')||'';if(!ct.includes('text/html'))return{item:null,hardReject:false};let finalUrl=r.url||start;if(urlGeneric(finalUrl))return{item:null,hardReject:true};let html=(await r.text()).slice(0,1900000);if(pageUnavailable(html))return{item:null,hardReject:true,unavailable:true};let found=[];for(const m of html.matchAll(/<script[^>]*type=[\"']application\/ld\+json[\"'][^>]*>([\s\S]*?)<\/script>/gi)){try{found.push(...productObjects(JSON.parse(m[1].trim())))}catch{}}let visible=visibleMainPrice(html),meta=metaMainPrice(html);for(const p of found){let title=cleanTitle(p.name||x.title);if(!specific(title,p.url||finalUrl,term))continue;let of=parseOffer(p.offers);if(!of||availabilityBad(of.availability))continue;let u=resolve(finalUrl,p.url||of.url||finalUrl);if(urlGeneric(u))continue;let chosen=visible||meta||of.price;if(!chosen)continue;return{item:{title,url:u,domain:host(u),ask:chosen,ship:of.ship,image:firstImage(p)||ogImage(html),availability:of.availability||'InStock',priceSource:visible?'PAGE_VISIBLE_MAIN_PRICE':meta?'PAGE_PRODUCT_META':'PAGE_PRODUCT_SCHEMA',priceVerified:true,shippingVerified:of.ship!==null,source:host(u),confidence:'high'},hardReject:false}}let title=cleanTitle((html.match(/<title[^>]*>([^<]+)<\/title>/i)||[])[1]||x.title),chosen=visible||meta;if(chosen&&specific(title,finalUrl,term))return{item:{title,url:finalUrl,domain:host(finalUrl),ask:chosen,ship:null,image:ogImage(html),availability:'InStock',priceSource:visible?'PAGE_VISIBLE_MAIN_PRICE':'PAGE_PRODUCT_META',priceVerified:true,shippingVerified:false,source:host(finalUrl),confidence:'high'},hardReject:false};return{item:null,hardReject:false}}
async function candidate(x,term=''){let p=await pageProduct(x,term);if(p.item)return{item:p.item,via:'page',unavailable:false};if(p.hardReject)return{item:null,via:'reject',unavailable:!!p.unavailable};let i=indexedProduct(x,term);if(i)return{item:i,via:'index',unavailable:false};return{item:null,via:'none',unavailable:false}}
function discoverNames(x,q,out){for(const pool of [x.product,x.product_cluster,x.schemas,x.deep_results]){if(!pool)continue;for(const p of productObjects(pool)){let n=cleanTitle(p.name||p.title||'');if(n&&relevant(q,n)&&!accessoryMismatch(q,n)&&!genericTitle(n,q)&&toks(n).length>=2)out.push(n)}}let n=cleanTitle(x.title);if(n&&relevant(q,n)&&!accessoryMismatch(q,n)&&!genericTitle(n,q)&&toks(n).length>=2)out.push(n)}
async function expandQuery(q,env){let rs=await brave(q+' modelli prodotti compra online Italia',env,10),names=[];for(const x of rs)discoverNames(x,q,names);let seen=new Set(),models=[];for(const n of names){let k=norm(n);if(!k||seen.has(k))continue;seen.add(k);models.push(n);if(models.length>=3)break}return{models,searchResults:rs.length}}
async function collect(term,env){let all=[],queries=0;for(const q of ['\"'+term+'\" prezzo compra online Italia','\"'+term+'\" offerta shop Italia']){let rs=await brave(q,env,10);queries++;all.push(...rs)}let seen=new Set(),results=[];for(const x of all){let k=x.url||x.title;if(!k||seen.has(k))continue;seen.add(k);results.push(x)}return{results:results.slice(0,14),queries,searchResults:all.length}}
function offerSort(a,b){let ta=(a.priceVerified?0:2)+(a.shippingVerified?0:1),tb=(b.priceVerified?0:2)+(b.shippingVerified?0:1);if(ta!==tb)return ta-tb;let pa=a.shippingVerified?a.ask+(a.ship||0):a.ask,pb=b.shippingVerified?b.ask+(b.ship||0):b.ask;return pa-pb}
async function searchExact(term,env){let sr=await collect(term,env),raw=[],pagesChecked=0,pageParsed=0,indexFallback=0,rejectedGeneric=0,rejectedUnavailable=0;for(const x of sr.results){if(urlGeneric(x.url)||genericTitle(x.title,term)){rejectedGeneric++;continue}let r=await candidate(x,term);pagesChecked++;if(r.unavailable){rejectedUnavailable++;continue}if(r.item&&similarity(term,r.item.title)>=.45){raw.push(r.item);if(r.via==='page')pageParsed++;else indexFallback++}}let seen=new Set(),items=[];for(const x of raw.sort(offerSort)){if(seen.has(x.url))continue;seen.add(x.url);items.push(x)}let verified=items.filter(x=>x.priceVerified).map(x=>x.ask+(x.shippingVerified?(x.ship||0):0)).filter(Number.isFinite),market=verified.length>=2?med(verified):null;if(market){let clean=verified.filter(p=>p>=market*.6&&p<=market*1.6);market=clean.length>=2?med(clean):market}items.sort(offerSort);let vr=0;items=items.slice(0,10).map((x,i)=>{if(x.priceVerified)vr++;return{...x,total:x.shippingVerified?x.ask+(x.ship||0):x.ask,totalKnown:!!x.shippingVerified,market:x.priceVerified?market:null,marketSamples:x.priceVerified?verified.length:0,marketSource:x.priceVerified&&market?'SAME_MODEL_VERIFIED_MEDIAN':null,modelQuery:term,rank:i+1,verifiedRank:x.priceVerified?vr:null}});let best=items.find(x=>x.priceVerified);if(best)best.bestVerified=true;else if(items[0])items[0].bestIndexed=true;return{items,stats:{queries:sr.queries,searchResults:sr.searchResults,pagesChecked,pageParsed,indexFallback,rejectedGeneric,rejectedUnavailable}}}
async function searchProduct(q,env){let first=await searchExact(q,env),models=[q],all=[...first.items],queries=first.stats.queries,searchResults=first.stats.searchResults,pagesChecked=first.stats.pagesChecked,pageParsed=first.stats.pageParsed,indexFallback=first.stats.indexFallback,rejectedGeneric=first.stats.rejectedGeneric,rejectedUnavailable=first.stats.rejectedUnavailable,broadQuery=false,expansionResults=0;if(first.items.length<3&&!modelToks(q).length){let e=await expandQuery(q,env);expansionResults=e.searchResults;if(e.models.length){broadQuery=true;models=e.models;all=[];for(const model of models){let r=await searchExact(model,env);all.push(...r.items);queries+=r.stats.queries;searchResults+=r.stats.searchResults;pagesChecked+=r.stats.pagesChecked;pageParsed+=r.stats.pageParsed;indexFallback+=r.stats.indexFallback;rejectedGeneric+=r.stats.rejectedGeneric;rejectedUnavailable+=r.stats.rejectedUnavailable}}}all.sort((a,b)=>{let ma=norm(a.modelQuery||''),mb=norm(b.modelQuery||'');return ma!==mb?ma.localeCompare(mb):offerSort(a,b)});return{items:all.slice(0,24),stats:{queries:queries+(broadQuery?1:0),searchResults:searchResults+expansionResults,pagesChecked,productsParsed:all.length,pageParsed,indexFallback,rejectedGeneric,rejectedUnavailable,broadQuery,expandedModels:models}}}
const DISCOVERY=['offerta smartphone compra online Italia','offerta console videogiochi compra online Italia','offerta notebook laptop compra online Italia','offerta tablet smartwatch compra online Italia','offerta fotocamera obiettivo compra online Italia','offerta cuffie auricolari compra online Italia','offerta robot aspirapolvere compra online Italia','offerta LEGO set compra online Italia','offerta monitor gaming compra online Italia','offerta SSD NVMe compra online Italia','offerta elettrodomestico cucina compra online Italia','offerta utensile elettrico compra online Italia'];
async function discover(env,offset=0){let rs=await brave(DISCOVERY[offset%DISCOVERY.length],env,10),raw=[],pagesChecked=0,pageParsed=0,indexFallback=0,rejectedGeneric=0,rejectedUnavailable=0;for(const x of rs){if(urlGeneric(x.url)||genericTitle(x.title,'')){rejectedGeneric++;continue}let r=await candidate(x,'');pagesChecked++;if(r.unavailable){rejectedUnavailable++;continue}if(r.item){raw.push(r.item);if(r.via==='page')pageParsed++;else indexFallback++}}let seen=new Set(),items=[];for(const x of raw.sort(offerSort)){if(seen.has(x.url))continue;seen.add(x.url);items.push({...x,total:x.shippingVerified?x.ask+(x.ship||0):x.ask,totalKnown:!!x.shippingVerified,market:null,marketSamples:0,modelQuery:x.title});if(items.length>=10)break}return{items,stats:{queries:1,searchResults:rs.length,pagesChecked,productsParsed:items.length,pageParsed,indexFallback,rejectedGeneric,rejectedUnavailable,broadQuery:false,expandedModels:[]}}}
export default{async fetch(req,env){if(req.method==='OPTIONS')return new Response('',{headers:CORS});let u=new URL(req.url);if(u.pathname==='/health')return json({ok:true,version:'1.12',brave:!!env.BRAVE_API_KEY});if(req.headers.get('x-dealhunter-key')!==env.SCANNER_KEY)return json({error:'unauthorized'},401);if(!env.BRAVE_API_KEY)return json({error:'BRAVE_API_KEY_missing'},500);if(req.method!=='POST')return json({error:'method_not_allowed'},405);let b=await req.json().catch(()=>({}));try{if(u.pathname==='/search'){let q=String(b.q||'').trim();if(!q)return json({error:'query_missing'},400);return json({ok:true,version:'1.12',mode:'search',query:q,generatedAt:new Date().toISOString(),...(await searchProduct(q,env))})}if(u.pathname==='/discover'){let offset=Math.abs(parseInt(b.offset||0,10))%DISCOVERY.length;return json({ok:true,version:'1.12',mode:'discover',offset,generatedAt:new Date().toISOString(),...(await discover(env,offset))})}return json({error:'not_found'},404)}catch(e){return json({error:String(e.message||e)},500)}}};