plugins {
    id 'com.android.application'
}

android {
    namespace 'com.colorpop.adventure'
    compileSdk 35

    defaultConfig {
        applicationId "com.colorpop.adventure"
        minSdk 24
        targetSdk 35
        versionCode 4
        versionName "0.54"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
